[project]
name = "steeleagle-aviary"
version = "0.1.3"
requires-python = ">=3.11"
dependencies = [
    "gabriel-protocol>=4.1",
    "grpcio>=1.76.0",
    "panda3d>=1.10.15",
    "pymap3d>=3.2.0",
    "pyzmq>=27.1.0",
    "colorhash",
    "opencv-python-headless",
    "steeleagle-protocol>=0.1.18",
    "toml>=0.10.2",
    "xdg-base-dirs>=6.0.2",
]

[project.scripts]
steeleagle-aviary = "steeleagle_aviary:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/steeleagle_aviary"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
