[[vehicles]]
name = "test-vehicle" # unique identifier for this vehicle
interface = "steeleagle_aviary.interfaces.steeleagle" # interface identifier (must be importable)
# origin coordinates
lat = 40.413664 
lon = -79.949285
alt = 0
    [vehicle.kwargs] # provide vehicle specific kwargs here

[[engines]]
name = "object-detector" # unique identifier of this engine
interface = "steeleagle_aviary.engines.detection" # interface identifier (must be importable)
    [engines.kwargs] # provide engine specific kwargs here

[[actors]]
name = 'test-target'
# Determines what type of object this is in the simulator
tag = 'person'
lat = 40.412654
lon = -79.948423
alt = 0
    [[actors.waypoints]] # waypoints the actor will navigate between
    lat = 40.412657
    lon = -79.948423
    alt = 0
    speed = 10 # speed at which the actor will navigate to this waypoint
