[project]
name = "parrot-anafi"
version = "0.1.7"
requires-python = ">=3.10,<=3.11"
dependencies = [
    "grpcio==1.50.0",
    "opencv-python-headless>=5.0.0.93",
    "parrot-olympe>=7.7.5,<8.0.0",
    "protobuf==3.19.4",
    "steeleagle-protocol",
]

[project.scripts]
parrot-anafi = "parrot_anafi:main"

[tool.uv.sources]
steeleagle-protocol = {path = "./steeleagle_protocol", editable = true}
parrot-olympe = { path = "./parrot_olympe-0.0.0-py3-none-manylinux_2_31_aarch64.whl", marker = "platform_machine == 'aarch64'" }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-order>=1.5.0",
]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
