[vehicle]
[vehicle.test1]
lat = 40.413633
lon = -79.949478
# List of cognitive engines, pair of name and kwargs
[vehicle.test1.engines]
object-detection = {}
# Vehicle kwargs
[vehicle.test1.kwargs]
address = 'unix:///tmp/test1-driver.sock'
tel_endpoint = 'unix:///tmp/test1-driver_telem.sock'
img_endpoint = 'unix:///tmp/test1-imagery.sock'
res_endpoint = 'unix:///tmp/test1-results.sock'

[vehicle.test2]
lat = 40.413664
lon = -79.949285
[vehicle.test2.engines]
object-detection = {}
[vehicle.test2.kwargs]
address = 'unix:///tmp/test2-driver.sock'
tel_endpoint = 'unix:///tmp/test2-driver_telem.sock'
img_endpoint = 'unix:///tmp/test2-imagery.sock'
res_endpoint = 'unix:///tmp/test2-results.sock'

[actor]
[actor.cube1]
# Determines what type of object this is in the simulator
tag = 'person'
lat = 40.412654
lon = -79.948423
#waypoints = [
#    {lat = ____, lon = ____, alt = ____}
#]
#velocity = ____
[actor.cube1.kwargs]
